#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
    if [ "$remote_ref" = "refs/heads/main" ] || [ "$remote_ref" = "refs/heads/master" ]; then
        echo "==========================================================="
        echo "🚨 ERROR: Push directo a 'main' interceptado."
        echo "     Por políticas de Enjambre (DOC-08),"
        echo "     está prohibido hacer push directo a main."
        echo "     Por favor crea un Pull Request."
        echo "==========================================================="
        exit 1
    fi
done

exit 0
