export default {
  id: 'grok',
  version: '2026.07.03.1',
  aliases: ['grok', 'groc', 'grok-build'],
  rules: [
    {
      id: 'option_dialog_blocked',
      state: 'blocked',
      priority: 320,
      region: 'whole_recent',
      visibleBlocker: true,
      lineRegex: ['^\\s*┃\\s+[0-9a-z]+\\s+\\([●○]\\)\\s'],
    },
    {
      id: 'permission_hints_blocked',
      state: 'blocked',
      priority: 310,
      region: 'bottom_non_empty_lines(2)',
      visibleBlocker: true,
      contains: [':select', 'ctrl+o:yolo', 'ctrl+c:cancel'],
    },
    {
      id: 'question_dialog_hints_blocked',
      state: 'blocked',
      priority: 305,
      region: 'bottom_non_empty_lines(2)',
      visibleBlocker: true,
      contains: ['tab:scrollback', 'shift+x:dismiss'],
    },
    {
      id: 'permission_scope_selector',
      state: 'blocked',
      priority: 300,
      region: 'whole_recent',
      visibleBlocker: true,
      contains: ['yes, proceed', 'no, reject'],
      any: [
        { contains: ['use ← → to choose permission whitelist scope'] },
        { contains: ['←/→:scope'] },
      ],
    },
    {
      id: 'spinner_status_working',
      state: 'running',
      priority: 200,
      region: 'whole_recent',
      visibleWorking: true,
      lineRegex: ['^\\s*[\\u2801-\\u28FF]\\s.*\\[stop\\]\\s*$'],
    },
    {
      id: 'esc_cancel_hints_working',
      state: 'running',
      priority: 190,
      region: 'bottom_non_empty_lines(2)',
      visibleWorking: true,
      contains: ['esc:cancel', 'ctrl+.:shortcuts'],
    },
    {
      id: 'waiting_tool_working',
      state: 'running',
      priority: 120,
      region: 'whole_recent',
      visibleWorking: true,
      any: [
        {
          all: [{ contains: ['ctrl+c:cancel', 'ctrl+enter:interject'] }, { contains: ['waiting'] }],
        },
        {
          lineRegex: ['^\\s*[\\u2801-\\u28FF]\\s+(Run|Read|Search|List)\\b'],
        },
      ],
    },
    {
      id: 'prompt_hints_idle',
      state: 'idle',
      priority: 100,
      region: 'bottom_non_empty_lines(2)',
      visibleIdle: true,
      contains: ['ctrl+.:shortcuts'],
      not: [{ contains: ['esc:cancel'] }, { contains: ['ctrl+c:cancel'] }],
    },
  ],
};
